/**
 * Product limits.
 *
 * claude.md § Visual keymap editor leaves these as "exact limits: TBD". They are
 * fixed here so validation is total rather than open-ended — an unbounded macro or
 * layer count is a resource-abuse vector, and the generator's output size must be
 * predictable before it reaches a compiler.
 *
 * These are product decisions, not QMK constraints. Raising one requires re-running
 * the compile smoke matrix, since generated size feeds directly into firmware size.
 */
export const LIMITS = {
  /** Layer 0 plus additional layers. QMK itself supports more; this is a product cap. */
  maxLayers: 8,
  /** Positions in a single layout we are willing to render and generate. */
  maxPositionsPerLayout: 512,
  maxMacros: 16,
  maxMacroSteps: 64,
  /** Milliseconds. A long delay blocks the keyboard's main loop. */
  maxMacroStepDelayMs: 5000,
  /** Sum of all delays in one macro. */
  maxMacroTotalDelayMs: 30000,
  maxConfigurationNameLength: 100,
  maxLayerNameLength: 40,
  maxMacroNameLength: 40,
  /** Hard cap on generated bytes across all emitted files, before compilation. */
  maxGeneratedBytes: 256 * 1024,
} as const;

export type Limits = typeof LIMITS;

/**
 * Build queue and retention policy.
 *
 * claude.md § Build isolation and security: "Limit concurrent builds per user/IP/
 * session and globally", and "use short retention by default". These numbers are the
 * concrete form of both sentences. They are deliberately conservative — a compile is
 * the most expensive thing this application does on behalf of an anonymous caller.
 */
export const BUILD_LIMITS = {
  /**
   * Total builds queued or running across every owner at once — the queue-depth cap
   * that protects the single build host regardless of how many distinct sessions are
   * asking. Queue depth is directly a wait time: depth × mean compile time ÷ worker
   * count. The host runs one worker, which compiles one build at a time, so at
   * ~60-120s per compile a depth of 8 is a worst case of roughly 8-16 minutes for the
   * last person in line — the edge of tolerable. 8 is also 4x `maxActiveBuildsPerOwner`,
   * so four distinct sessions can each hold their full allowance before this cap bites.
   * Tuning trigger: raise it when more than one worker runs, in proportion to worker
   * count — not in response to a single busy hour.
   */
  maxGlobalActiveBuilds: 8,
  /**
   * Builds one session may have queued or running at once. A session that wants a
   * different result cancels or waits; it cannot occupy the queue.
   */
  maxActiveBuildsPerOwner: 2,
  /** Builds one session may request per rolling hour, finished or not. */
  maxBuildsPerOwnerPerHour: 20,
  /**
   * How long a worker's claim on a build stays valid without a heartbeat. Longer than
   * any single compile step, short enough that a crashed worker frees its build
   * promptly.
   */
  buildLeaseMs: 120_000,
  /** Heartbeat interval; comfortably inside the lease so a slow tick is not fatal. */
  buildHeartbeatMs: 20_000,
  /**
   * Attempts before a build is failed rather than requeued. A build reclaimed from a
   * dead worker is retried; one that kills every worker it touches is not.
   */
  maxBuildAttempts: 3,
  /** Artifact retention. Short by default; a user re-builds rather than relying on us. */
  artifactRetentionMs: 7 * 24 * 60 * 60 * 1000,
  /** Log retention, independent of the artifact: a failed build has a log and no artifact. */
  logRetentionMs: 7 * 24 * 60 * 60 * 1000,
} as const;

export type BuildLimits = typeof BUILD_LIMITS;

/**
 * Session-issuance abuse control.
 *
 * D-12: minting a fresh anonymous session is the cheap step that defeats every
 * per-owner build quota — a caller who cannot get another build under one identity
 * simply mints a new one. This is the single IP-scoped control that closes that hole;
 * once it holds, `BUILD_LIMITS.maxActiveBuildsPerOwner` /
 * `BUILD_LIMITS.maxBuildsPerOwnerPerHour` do their job again and a per-IP build quota
 * is largely redundant.
 *
 * `issuancePerIpPerHour` is 120, over a rolling one-hour window. A legitimate visitor
 * mints exactly one session per browser per year — the cookie's Max-Age is a
 * deliberate one year — so 120 first-time visitors per hour from one address is
 * generous for an office or campus behind a single NAT, which is exactly the case
 * D-12 asks to protect. It simultaneously caps the fresh-session churn an attacker
 * needs to route around the per-owner quotas at 120/hour/address; the global
 * queue-depth cap (`BUILD_LIMITS.maxGlobalActiveBuilds`) remains the backstop that
 * does not care how many identities are in play.
 *
 * Limitation that must stay visible here, not just in a design doc: this counter is
 * in-process. With more than one API process the effective limit multiplies by the
 * process count. That is tolerable only because this is not the load-bearing
 * control — the global build cap is enforced in Postgres and is correct across
 * processes regardless of how many session-issuance buckets exist.
 */
export const SESSION_LIMITS = {
  issuancePerIpPerHour: 120,
  /** The rolling window `issuancePerIpPerHour` is measured over, in milliseconds. */
  issuanceWindowMs: 60 * 60 * 1000,
} as const;

export type SessionLimits = typeof SESSION_LIMITS;
