/**
 * Product limits.
 *
 * claude.md § Visual keymap editor leaves these as "exact limits: TBD". They are
 * fixed here so validation is total rather than open-ended — an unbounded macro or
 * layer count is a resource-abuse vector, and the generator's output size must be
 * predictable before it reaches a compiler.
 *
 * These are product decisions, not QMK constraints. Raising one requires re-running
 * the compile smoke matrix, since generated size feeds directly into firmware size.
 */
export const LIMITS = {
  /** Layer 0 plus additional layers. QMK itself supports more; this is a product cap. */
  maxLayers: 8,
  /** Positions in a single layout we are willing to render and generate. */
  maxPositionsPerLayout: 512,
  maxMacros: 16,
  maxMacroSteps: 64,
  /** Milliseconds. A long delay blocks the keyboard's main loop. */
  maxMacroStepDelayMs: 5000,
  /** Sum of all delays in one macro. */
  maxMacroTotalDelayMs: 30000,
  maxConfigurationNameLength: 100,
  maxLayerNameLength: 40,
  maxMacroNameLength: 40,
  /** Hard cap on generated bytes across all emitted files, before compilation. */
  maxGeneratedBytes: 256 * 1024,
} as const;

export type Limits = typeof LIMITS;

/**
 * Build queue and retention policy.
 *
 * claude.md § Build isolation and security: "Limit concurrent builds per user/IP/
 * session and globally", and "use short retention by default". These numbers are the
 * concrete form of both sentences. They are deliberately conservative — a compile is
 * the most expensive thing this application does on behalf of an anonymous caller.
 */
export const BUILD_LIMITS = {
  /**
   * Total builds queued or running across every owner at once — the queue-depth cap
   * that protects the single build host regardless of how many distinct sessions are
   * asking. Queue depth is directly a wait time: depth × mean compile time ÷ worker
   * count. The host runs one worker, which compiles one build at a time, so at
   * ~60-120s per compile a depth of 8 is a worst case of roughly 8-16 minutes for the
   * last person in line — the edge of tolerable. 8 is also 4x `maxActiveBuildsPerOwner`,
   * so four distinct sessions can each hold their full allowance before this cap bites.
   * Tuning trigger: raise it when more than one worker runs, in proportion to worker
   * count — not in response to a single busy hour.
   */
  maxGlobalActiveBuilds: 8,
  /**
   * Builds one session may have queued or running at once. A session that wants a
   * different result cancels or waits; it cannot occupy the queue.
   */
  maxActiveBuildsPerOwner: 2,
  /** Builds one session may request per rolling hour, finished or not. */
  maxBuildsPerOwnerPerHour: 20,
  /**
   * How long a worker's claim on a build stays valid without a heartbeat. Longer than
   * any single compile step, short enough that a crashed worker frees its build
   * promptly.
   */
  buildLeaseMs: 120_000,
  /** Heartbeat interval; comfortably inside the lease so a slow tick is not fatal. */
  buildHeartbeatMs: 20_000,
  /**
   * Attempts before a build is failed rather than requeued. A build reclaimed from a
   * dead worker is retried; one that kills every worker it touches is not.
   */
  maxBuildAttempts: 3,
  /** Artifact retention. Short by default; a user re-builds rather than relying on us. */
  artifactRetentionMs: 7 * 24 * 60 * 60 * 1000,
  /** Log retention, independent of the artifact: a failed build has a log and no artifact. */
  logRetentionMs: 7 * 24 * 60 * 60 * 1000,
} as const;

export type BuildLimits = typeof BUILD_LIMITS;
